Trylma/Trylma/Models/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Trylma.Models
{
    public class Message
    {
        public User Sender { get; private set; }
        public string Msg { get; private set; }
        public string Time { get; private set; }
        public bool Special { get; private set; }

        public Message(User u, string m, bool special = false)
        {
            Sender = u;
            Msg = m;
            Special = special;
            Time = String.Format("{0:d/M/yyyy HH:mm:ss}", DateTime.Now);
        }
    }
}

Trylma/Trylma/Models/Room.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Trylma.Helpers;

namespace Trylma.Models
{
    public class GameRoom
    {
        public List<User> UserQueue;
        public List<Message> Messages;
        public Game Game;
        public User Owner;
        public int GameId;

        public GameRoom(User user)
        {
            Owner = user;
            UserQueue = new List<User>();
            Messages = new List<Message>();
            UserQueue.Add(DBContext.GetUserByLogin("HeuristicAI"));
            UserQueue.Add(DBContext.GetUserByLogin("MinMaxAI"));
            GameId = Platform.Games.Count == 0 ? 1 : Platform.Games.FindLast(game => game.GameId < int.MaxValue).GameId + 1; //TODO: Find a way to get first non-existing number in set
            Game = new Game(GameId, user, this);
        }

        public void Open()
        {
            UserQueue.Clear();
            Messages.Clear();
            Messages.Add(new Message(Owner, "[Otwarcie gry]", special: true));
            Game.Open();
        }

        public bool UserParticipate(string userName)
        {
            bool result = !(UserQueue.Where(u => u.Name == userName).FirstOrDefault() == null && Game.HasUser(userName) == false);
            return result;
        }

        public IEnumerable<User> GetParticipants()
        {
            return Game.Players.Where(p => p.Type == PlayerType.Human).Select(p => p.User).Concat(UserQueue);
        }

        public void SetReady(string username)
        {
            Player pl = Game.Players.Where(p => p.User.Name == username).FirstOrDefault();
            if (pl != null)
            {
                pl.Ready = true;
                if (AllPlayersReady()) Game.Start();
                Game.GameHub.OnRoomChange(this, pl.Id, -1);
            }
        }

        public bool AllPlayersReady()
        {
            return Game.Players.Where(pl => pl.Ready == false).FirstOrDefault() == null;
        }

        public bool Join(User user) 
        {
            if (Game.State != GameState.Started && UserQueue.Where(u => u.Name == user.Name).FirstOrDefault() == null)
                UserQueue.Add(user);

            if (Game.Clients.Where(c => c.User.Name == user.Name).FirstOrDefault() == null)
            {
                Game.Clients.Add(new GameClient { User = user, EndedMove = Game.Move });
                Game.GameHub.OnRoomChange(this, -1, user.Id);
                return true;
            }

            Game.UserJoinGame(user.Name);

            if (Game.State == GameState.Started)
            {
                Game.NextMove();
            }

            Game.GameHub.OnRoomChange(this, -1, user.Id);
            return false;
        }

        public bool IsInactive()
        {
            if (Game.IsGameOver)
            {
                foreach (var c in Game.Clients)
                {
                    if (c.Active == true) return false;
                }
                return true;
            }
            return false;
        }

        public bool Leave(User user)
        {
            Game.UserLeftGame(user.Name);
            if (UserParticipate(user.Name) == true)
            {
                if (Game.State == GameState.Opened)
                {
                    UserQueue.Remove(UserQueue.Where(u => u.Name == user.Name).FirstOrDefault());
                    Player player = Game.Players.Where(pl => pl.User == user).FirstOrDefault();

                    if (player != null)
                        Game.RemovePlayer(player.Id);
                }

                Game.GameHub.OnRoomChange(this, -1, user.Id);
                return true;
            }
            Game.GameHub.OnRoomChange(this, -1, -1);
            return false;
        }

        public void AddPlayer(User us)
        {
            if (Game.AddPlayer(us) == true)
            {
                if (Game.State == GameState.Opened)
                {
                    UserQueue.Remove(UserQueue.Where(u => u.Name == us.Name).FirstOrDefault());
                }
                Game.GameHub.OnRoomChange(this, Game.Players.Last().Id, -1);
            }
        }

        public void RemovePlayer(int playerId)
        {
            User user = Game.RemovePlayer(playerId);
            if (user != null)
            {
                if (Game.State == GameState.Opened)
                {
                    Game.Room.UserQueue.Add(user);
                }
                Game.GameHub.OnRoomChange(Game.Room, -1, user.Id);
            }
        }


        public void AddMessage(Message msg)
        {
            Messages.Add(msg);
        }
    }
}

Trylma/Trylma/Models/RoomTable.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Trylma.Models
{
    public class RoomTable
    {
        public GameRoom Room;
        public User NewUser;
        public Player NewPlayer;

        public RoomTable() { }
        public RoomTable(GameRoom gr, User nu, Player np)
        {
            NewUser = nu;
            NewPlayer = np;
            Room = gr;
        }
    }
}

Trylma/Trylma/Controllers/GameRoomController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Trylma.Helpers;
using Trylma.Models;

namespace Trylma.Controllers
{
    public class GameRoomController : Controller
    {
        [HttpGet]
        public ActionResult Create()
        {
            User user = DBContext.GetUserByLogin(User.Identity.Name);
            GameRoom room = new GameRoom(user);
            Platform.Games.Add(room);
            ViewBag.GameDesc = room.Game.GetDesc();
            return RedirectToAction("Index", new { room.GameId });
        }

        public ActionResult Index(int gameId)
        {
            try
            {
                Game game = Platform.GetGameById(gameId, User.Identity.Name);
                ViewBag.GameDesc = game.GetDesc();
                return View(game.Room);
            }
            catch (Errors.GameNotFound e) {
                return View("Error", e);
            }
        }

        public JsonResult Open(int gameId)
        {
            try 
            { 
                GameRoom room = Platform.GetRoomById(gameId, User.Identity.Name);
                room.Open();
                room.Game.GameHub.OnRoomChange(room, room.Game.Players.Last().Id, -1);
                return Json(true);
            }
            catch (Errors.GameNotFound e)
            {
                return Json(false);
            }
        }


        [HttpPost]
        public JsonResult AddMessage(int gameId, string msg)
        {
            try
            {
                GameRoom room = Platform.GetRoomById(gameId, User.Identity.Name);
                User user = DBContext.GetUserByLogin(User.Identity.Name);

                Message mess = new Message(user, msg);
                NewMessage(mess, room);
                return Json(true);
            }
            catch (Exception e)
            {
                return Json(false);
            }
        }


        [HttpPost]
        public JsonResult LeaveRoom(int gameId)
        {
            try
            {
                User me = DBContext.GetUserByLogin(User.Identity.Name);
                GameRoom room = Platform.GetRoomById(gameId, User.Identity.Name);

                room.Leave(me);
                if (room.IsInactive()) Platform.Games.Remove(room);
                NewMessage(new Message(me, "[Wychodzi]"), room);
                return Json(true);
            }
            catch (Exception e)
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult JoinRoom(int gameId)
        {
            try
            { 
                User me = DBContext.GetUserByLogin(User.Identity.Name);
                GameRoom room = Platform.GetRoomById(gameId, User.Identity.Name);
                room.Join(me);
                NewMessage(new Message(me, "[Wchodzi]"), room);
                return Json(true);
            }
            catch (Exception e)
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult AddPlayer(int gameId, string userName)
        {
            try 
            { 
                GameRoom room = Platform.GetRoomById(gameId, User.Identity.Name);
                User user = DBContext.GetUserByLogin(userName);
                room.AddPlayer(user);
            }
            catch (Exception e)
            {
                return Json(false);
            }
            return Json(true);
        }

        [HttpPost]
        public JsonResult RemovePlayer(int gameId, int playerId)
        {
            try
            {
                GameRoom room = Platform.GetRoomById(gameId, User.Identity.Name);
                room.RemovePlayer(playerId);
            }
            catch (Exception e)
            {
                return Json(false);
            }
            return Json(true);
        }

        [HttpPost]
        public JsonResult Update(int gameId, int newPlayerId, int newUserId)
        {
            try
            { 
                Game game = Platform.GetGameById(gameId, User.Identity.Name);
                UpdateRoomTable(game.Room, newPlayerId, newUserId);
                game.GameHub.RefreshBoard(game.Room);
                return Json(true);
            }
            catch (Errors.GameNotFound e) { 
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult SetReady(int gameId)
        {
            try
            {
                Debug.WriteLine(User.Identity.Name + " SetReady");
                GameRoom room = Platform.GetRoomById(gameId, User.Identity.Name);
                room.SetReady(User.Identity.Name);
                return Json(true);
            }
            catch (Exception e)
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult GetGame(int gameId)
        {
            try
            {
                Debug.WriteLine(User.Identity.Name + " GetGame");
                GameRoom room = Platform.GetRoomById(gameId, User.Identity.Name);
                return Json(true);
            }
            catch (Exception e)
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult GetGameOverInfo(int gameId)
        {
            try 
            { 
                GameRoom room = Platform.GetRoomById(gameId, User.Identity.Name);

                string html = PartialView("GameOver", room.Game.Players).RenderToString();
                return Json(html);
            }
            catch (Errors.GameNotFound e)
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult StartGame(int gameId)
        {
            try
            {
                Debug.WriteLine(User.Identity.Name + " StartGame");
                Game game = Platform.GetGameById(gameId, User.Identity.Name);
                if (game.State != GameState.Started)
                {
                    game.Start();
                    game.GameHub.OnRoomChange(game.Room, -1, -1);
                    return Json(true);
                }
                return Json(false);
            }
            catch (Errors.GameNotFound e)
            {
                return Json(false);
            }
        }


        //wysyłają partial views przez signalR
        private void SendGame(GameRoom room) 
        {
            string html = PartialView("GameHUD", room.Game).RenderToString();
            room.Game.GameHub.SendGameArea(User.Identity.Name, html, room.Game);
        }

        public JsonResult SetBoardSize(int gameId, int boardSize)
        {
            try
            {
                Game game = Platform.GetGameById(gameId, User.Identity.Name);
                game.SetBoardSize((BoardSize)boardSize);
                ViewBag.GameDesc = game.GetDesc();
                return Json(new
                {
                    result = true,
                    game = Json(game.GetDesc())
                });
            }
            catch (Errors.GameNotFound e)
            {
                return Json(new
                {
                    result = false,
                });
            }
        }

        private void UpdateRoomTable(GameRoom room, int newplid, int newuid)
        {
            if (room.Game.State == GameState.Configured)
            {
                RoomTable rt = new RoomTable
                {
                    Room = room,
                    NewUser = DBContext.GetUserById(newuid),
                    NewPlayer = room.Game.Players.Where(pl => pl.Id == newplid).FirstOrDefault()
                };
                string html = PartialView("Config", rt).RenderToString();
                room.Game.GameHub.UpdateRoom(room, User.Identity.Name, html);
            }
            else if (room.Game.State == GameState.Opened)
            {
                RoomTable rt = new RoomTable
                {
                    Room = room,
                    NewUser = DBContext.GetUserById(newuid),
                    NewPlayer = room.Game.Players.Where(pl => pl.Id == newplid).FirstOrDefault()
                };
                string html = PartialView("RoomTable", rt).RenderToString();
                room.Game.GameHub.UpdateRoom(room, User.Identity.Name, html);
            }
            else if (room.Game.State == GameState.Started)
            {
                SendGame(room);
            }
        }

        private void NewMessage(Message msg, GameRoom room)
        {
            room.AddMessage(msg);
            room.Game.GameHub.OnMessage(PartialView("_Message", msg).RenderToString(), room);
        }
    }
}

Trylma/Trylma/Controllers/PlatformController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trylma.Helpers;
using Trylma.Models;

namespace Trylma.Controllers
{
    public class PlatformController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("OpenedGames");
        }

        public ActionResult RankingList()
        {
            return View("RankingList", DBContext.GetRankingList());
        }

        public ActionResult OpenedGames()
        {
            ViewBag.GameState = (int)GameState.Opened;
            return View("ListOfGames", Platform.Games.Where(g => g.Game.State == GameState.Opened).ToList());
        }

        public ActionResult MyGames()
        {
            ViewBag.GameState = (int)GameState.Started + 1;
            return View("ListOfGames", Platform.Games.Where(g => g.Game.State == GameState.Started && g.Game.HasUser(User.Identity.Name)).ToList());
        }

        public ActionResult StartedGames()
        {
            ViewBag.GameState = (int)GameState.Started;
            return View("ListOfGames", Platform.Games.Where(g => g.Game.State == GameState.Started).ToList());
        }

        public ActionResult Profile()
        {
            return View(DBContext.GetUserByLogin(User.Identity.Name));
        }

    }
}

Trylma/Trylma/Views/Shared/Config.cshtml
@model Trylma.Models.RoomTable

<div class="box">
    <div class="ui segment">
        Wielkość planszy:<br/>

            <select id="boardSize" onchange="changeBoardSize()" class="ui dropdown">
                <option value="0">Mała</option>
                <option value="1">Średnia</option>
                <option value="2">Duża</option>
            </select>
        </div>
</div>
@Html.Partial("ConfigTable", @Model)

<script>
    $('#boardSize').val(@Model.Room.Game.GetDesc().BoardSize);
</script>

Trylma/Trylma/Views/Shared/ConfigTable.cshtml
@model Trylma.Models.RoomTable

<table style="width:100%">
    <tr>
        <td><b>Gracze</b></td>
        <td><b>Dodaj graczy</b></td>
    </tr>
    <tr>
        <td>
            @foreach (var player in Model.Room.Game.Players)
            {
                <div class="box player @(Model.NewPlayer == player ? "new" : "")">
                    <div class="ui segment">
                        @Html.Partial("_PlayerPartial", @player)

                        @if (@Model.Room.Owner.Name == User.Identity.Name)
                        {
                            <button class="ui button red conf" onclick="removePlayer(this.id)" id="@player.Id">Usuń</button>
                        }
                    </div>
                </div>
            }
        </td>
        <td>
            <div class="userqueuearea">
                @foreach (var user in @Model.Room.UserQueue)
                {
                    <div class="box user @(Model.NewUser == user ? "new" : "")" id="@user.Name">
                        <div class="ui segment">
                            @Html.Partial("_UserPartial", @user)
                                @if (@Model.Room.Owner.Name == User.Identity.Name)
                                {
                                    <button class="ui button blue conf" onclick="addPlayer(this.id)" id="@user.Name">Dodaj</button>
                                }
                        </div>
                    </div>
                }

            </div>
        </td>
    </tr>
</table>
<div class="box">
    <div class="ui segment">
        <button class="ui button green" id="openGame" onclick="openGame()" title="Otwórz grę">Otwórz</button>
        <button class="ui button green" id="startGame" onclick="startGame()" title="Rozpocznij grę jednoosobową">Graj</button>
    </div>
</div>

Trylma/Trylma/Views/Shared/GameHUD.cshtml
@model Trylma.Models.Game

@foreach (var player in @Model.Players)
{
    <div class="box" id="@player.Id">
        <div class="ui segment @(player.IsConnected() == false ? " disscon" : "")">
            @Html.Partial("_PlayerPartial", @player)
        </div>
    </div>
}

Trylma/Trylma/Views/Shared/GameOver.cshtml
@model List<Trylma.Models.Player>

<div class="box new" id="gameoverinfo">
    <div class="ui segment">

    Gra zakończona! Gratulacje!    

    <ul style="list-style: none">
        @foreach (Trylma.Models.Player pl in Model)
        {
            <li>
                <img src="@pl.User.AvatarPath" width="45" height="45" style="vertical-align:middle" />
                @pl.Name
                <img src="~/Resources/Images/star.png" style="vertical-align: middle" width="15" height="15" />
                <span style="font-size: 20px;">
                    @pl.IncreaseOfRanking
                </span>
            </li>
        }
    </ul>

    </div>
</div>

Trylma/Trylma/Views/Shared/GameView.cshtml
@model Trylma.Models.Game


<table style="width: 100%">
    <tr>
        <td style="vertical-align: top; width: 40%">
            <canvas id="canvas" width="600" height="@(Model.GameBoard.Height*36)" float: left"></canvas>
        </td>
        <td>
            @Html.Partial("GameHUD", @Model)
        </td>
    </tr>
</table>
<!--
<p id="output"></p>
Gracz:
<p id="currentPlayer"></p>
Rysuj wsp:
<input type="checkbox" onclick="chckbDrawCoords(this)" />-->

@section Scripts {
    <script>
        var game = new Game();

        function SignalRCompleted() {
            game.init(@Html.Raw(Json.Encode(ViewBag.GameDesc)));
        }
    </script>

    <script src="/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script src="/signalr/hubs"></script>
    <script src="/Scripts/GameHub.js"></script>

    <script>
        Config.user = "@User.Identity.Name";
            //debug mode
            function chckbDrawCoords(o) {
                game.getBoardView().drawCoords = o.checked;
                game.getBoardView().redrawBoard();
            }
        
    </script>
}

Trylma/Trylma/Views/Shared/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Trylma Platform</title>

    <style type="text/css">
        * {
            font-family: 'Calibri', sans-serif !important;
        }
    </style>

</head>
<body>
    @if (User.Identity.IsAuthenticated) 
    {
        <div class="box"><div class="ui segment">
            
            <img src="@Trylma.Helpers.DBContext.GetUserByLogin(User.Identity.Name).AvatarPath" width="45" height="45" style="vertical-align:middle"/>
            Jesteś zalogowany jako @User.Identity.Name
            <a href="@Url.Action("logout", "authorization")" class="menu">Wyloguj</a>
            
            <br/><br />
            <div><!--
                <a href="@Url.Action("Index", "Platform")" class="menu">Home</a>
                <a href="@Url.Action("Profile", "Platform")" class="menu">Profil</a>-->

                <button class="ui button blue" onclick='window.location.href = "@Url.Action("Index", "Platform")"'>Home</button>
                <button class="ui button blue" onclick='window.location.href = "@Url.Action("Profile", "Platform")"'>Profil</button>
                <button class="ui button blue" onclick='window.location.href = "@Url.Action("RankingList", "Platform")"'>Ranking</button>

                <button class="ui button green" onclick='window.location.href = "@Url.Action("Create", "GameRoom")"' 
                        style="float: right" id="createGameButton">+ Stwórz nową grę</button>
            </div>
        </div></div>
        
        
    }
    <div>
        @RenderBody()
    </div>
</body>

    <link rel="stylesheet" href="/Styles/GameBoard.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="/Styles/style.css">
    <link rel="stylesheet" href="/Styles/semantic.min.css">

    <script src="/Scripts/base.js"></script>
    <script src="/Scripts/Config.js"></script>
    <script src="/Scripts/Board.js"></script>
    <script src="/Scripts/BoardView.js"></script>
    <script src="/Scripts/Player.js"></script>
    <script src="/Scripts/Game.js"></script>
    <script src="/Scripts/Game.js"></script>
    <script src="/Scripts/jquery-2.1.4.min.js"></script>

    
    @*////////////////////////////////////////////////////////////////////////////////////////////// *@

    @RenderSection("Scripts", required: false)

    
</html>

Trylma/Trylma/Views/Shared/RoomTable.cshtml
@model Trylma.Models.RoomTable

<table style="width: 100%">
    <tr>
        <td><b>Gracze</b></td>
        <td><b>Dodaj graczy</b></td>
    </tr>
    <tr>
        <td>
            @foreach (var player in Model.Room.Game.Players)
            {
                <div class="box player @(Model.NewPlayer == player ? "new" : "")">
                    <div class="ui segment">
                        @Html.Partial("_PlayerPartial", @player)

                        @if (player.Ready == true)
                        {
                            <text>[Gotowy]</text>
                        }

                        @if (player.Type == Trylma.Models.PlayerType.Human &&
                            @Model.Room.Owner.Name == User.Identity.Name &&
                            player.Ready != true)
                        {
                            <button class="ui button red" onclick="removePlayer(this.id)" id="@player.Id">Usuń</button>
                        }
                    </div>
                </div>
            }
        </td>
        <td>
            <div class="userqueuearea">
                @foreach (var user in @Model.Room.UserQueue)
                {
                    <div class="box user @(Model.NewUser == user ? "new" : "")" id="@user.Name">
                        <div class="ui segment">
                            @Html.Partial("_UserPartial", @user)
                            @if (@Model.Room.Owner.Name == User.Identity.Name)
                            {
                                <button class="ui button blue" onclick="addPlayer(this.id)" id="@user.Name">Dodaj</button>
                            }
                        </div>

                    </div>
                }

            </div>
        </td>
    </tr>
</table>
@if (Model.Room.Game.HasUser(User.Identity.Name))
{
<div class="box @(Model.NewPlayer !=null && Model.NewPlayer.User.Name == User.Identity.Name ? "new" : "")">
    <div class="inner">
        <button class="ui button green" id="readyGame" onclick="setReady()" title="Rozpocznij grę">Jestem gotowy!</button>
    </div>
</div>
}

Trylma/Trylma/Views/Shared/_Message.cshtml
@model Trylma.Models.Message

<div class="ui segment msg">
        <img src="@Model.Sender.AvatarPath" width="30" height="30" style="vertical-align:middle"/>
        
    @if (Model.Special == true)
    {
        <span style="vertical-align: middle;" class="specialmsg">
            @Model.Time
            <b>@Model.Sender.Name:</b>
            @Model.Msg
        </span>
    }
    else
    {
        <span style="vertical-align: middle;">
            @Model.Time
            <b>@Model.Sender.Name:</b>
            @Model.Msg
        </span>
    }    
</div>

Trylma/Trylma/Views/Shared/_PlayerDescription.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_PlayerDescription</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>

Trylma/Trylma/Views/Shared/_PlayerPartial.cshtml
@model Trylma.Models.Player

<span @(Model.Name == User.Identity.Name ? "class=me" : "")>
    <img src="@Model.User.AvatarPath" width="45" height="45" style="vertical-align:middle" />
    <span style="vertical-align: middle;">
        @Model.Name
        <img src="~/Resources/Images/star.png" width="20" height="20" style="vertical-align: middle" />
        @Model.User.Ranking
    </span>
    <div class="circle" style="background-color: @Model.Color"></div>
</span>

Trylma/Trylma/Views/Shared/_UserPartial.cshtml
@model Trylma.Models.User

<span @(Model.Name == User.Identity.Name ? "class=me" : "")>
    <img src="@Model.AvatarPath" width="45" height="45" style="vertical-align:middle" />

    <span style="vertical-align: middle;">
        @Model.Name
        <img src="~/Resources/Images/star.png" width="20" height="20" style="vertical-align: middle" />
        @Model.Ranking
    </span>
</span>